app7/urls.py
from django.urls import path
from app7.views import *
app_name='srikanth'
urlpatterns=[
    path('third/',third,name='third')
]

p8/urls.py
from django.contrib import admin
from django.urls import path,include
from app7.views import *
import app7


urlpatterns = [
    path('admin/', admin.site.urls),
    path('first/',first,name='first'),
    path('second/',second,name='second'),
    path('app7/',include('app7.urls')),

]

app7/models.py
from django.db import models

# Create your models here.

app7/views.py
from django.shortcuts import render

# Create your views here.
def first(request):
    return render(request,'first.html')
def second(request):
    return render(request,'second.html') 
def third(request):
    return render(request,'third.html')    

templates/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=<>, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is my first html page</h1>
        <h2>connect to second html page</h2>
        <h3>connect to third html page</h3>
        <a href="{% url 'second' %}">click on the second html page</a>
        <br/>
        <a href="{% url 'srikanth:third' %}">click on the third html page</a>
    </center>    
</body>
</html>

templates/second.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=<>, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is second html page</h1>
        <h2>connect with first html page</h2>
        <a href="{% url 'first' %}">click on the first html page</a> 

    </center>
</body>
</html>

templates/third.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>this is my third html page</h1>
        <h2>connect with second html page</h2>
        <a href="{% url 'second' %}">click on the second html page</a>
    </center>    
</body>
</html>